# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

LIMIT = 4000000

def generate_fibo(number_list, limit):
    new_number = number_list[-2] + number_list[-1]
    if new_number > limit:
        return number_list
    else:
        number_list.append(new_number)    
        return generate_fibo(number_list, limit)

def even_numbers_sum(number_list):
    return sum([n for n in number_list if n % 2 == 0])

numbers = generate_fibo([1,2], LIMIT)
print "Sum is %d" % even_numbers_sum(numbers)